version: '3'
services:
  httpd:
    build:
      context: .
      dockerfile: httpd.Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./backend:/var/www/html
    networks:
      - httpdphpfpm

  phpfpm:
    image: php:7.4-fpm
    expose:
      - 9000
    volumes:
      - ./backend:/var/www/html
    networks:
      - httpdphpfpm

networks:
  httpdphpfpm:
    driver: bridge