version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_pw_shh
      MYSQL_DATABASE: test_db
      MYSQL_USER: devuserd
      MYSQL_PASSWORD: devpass
    ports:
      - "9906:3306"
    volumes:
      - /var/lib/mysql
    networks:
      - internal

  php-apache-environment:
    container_name: php-apache
    image: php:8.0-apache
    volumes:
      - ./backend:/var/www/html/
    ports:
      - 8080:80
    networks:
      - internal

      
networks:
  internal:
    driver: bridge