version: '3'
services:
  httpd:
    build:
      context: .
      dockerfile: httpd.Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./backend:/var/www/html
    links:
      - db
    networks:
      - httpdphpfpm

  phpfpm:
    build:
      context: .
      dockerfile: phpfpm.Dockerfile
    image: php
    expose:
      - 9000
    volumes:
      - ./backend:/var/www/html
    networks:
      - httpdphpfpm
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - KEY_JWT=${KEY_JWT}
  db:
    image: mysql:5.7
    container_name: db
    command: mysqld --user=${MYSQL_USER}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "6033:3306"
    networks:
      - httpdphpfpm
    volumes:
      - dbdata:/var/lib/mysql
      - ./database/dump.sql:/docker-entrypoint-initdb.d/dump.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      - PMA_HOST=${MYSQL_HOST}
      - PMA_PORT=${MYSQL_PORT}
      - PMA_USER=${MYSQL_USER}
      - PMA_PASSWORD=${MYSQL_PASSWORD}
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8081:80
    networks:
      - httpdphpfpm

networks:
  httpdphpfpm:
    driver: bridge

volumes:
  dbdata: