version: '3'
services:
  httpd:
    build:
      context: .
      dockerfile: httpd.Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./backend:/var/www/html
    networks:
      - httpdphpfpm

  phpfpm:
    build:
      context: .
      dockerfile: phpfpm.Dockerfile
    image: php
    expose:
      - 9000
    volumes:
      - ./backend:/var/www/html
    networks:
      - httpdphpfpm

  db:
    image: mysql:5.7
    container_name: db
    command: mysqld --user=mysql
    environment:
      MYSQL_ROOT_PASSWORD: hH!X6A4Y6UAt
      MYSQL_DATABASE: app_db
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: hH!X6A4Y6UAt
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80

networks:
  httpdphpfpm:
    driver: bridge

volumes:
  dbdata: